config/routes.rb
Rails.application.routes.draw do
  # get 'products/index'
  # get 'products/new'
  # get 'products/show'
  devise_for :users, controllers: { registrations: "users/registrations" }

  # EVENTS--------------------------
  # get 'events/index'
  # get 'events/show'
  # get 'events/edit'
  # get 'events/update'
  # get 'events/new'
  # get 'events/create'
  # get 'events/destroy'

  get "my-events", to: "events#my_events", as: "my_events"
  get "my-events/new", to: "events#new_my_event", as: "new_my_event"

  # PAGES ------------------------
  get "/dashboard", to: "pages#dashboard"
  get "/analytics", to: "pages#analytics"
  get "/settings", to: "pages#settings"
  get "/favourites", to: "pages#favourites"

  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  get '/search', to: 'searches#search', as: :search

  # FARMERS, CRATES AND POSTS --------------
  resources :farmers, exclude: [:destroy] do
    resources :crates, only: [:index, :show, :edit, :update, :destroy]
    resources :posts, only: [:index, :show, :edit, :update, :destroy ] do
      resources :likes, only: [:create, :destroy]
    end
    resources :reviews, only: [:new, :create]
  end

  #  TEMP FOLLOW ROUTES: DELETE IF INTRODUCE BUGS
  resources :farmers, only: [:index, :show] do
    post 'follow', to: 'farmers#follow'
    delete 'unfollow', to: 'farmers#unfollow'
  end

  # This version removed the index etc in the array to make searches work
  resources :crates, only: [] do
    resources :orders, only: [:new, :create]
  end
  get "orders/:id/order_confirmation", to: "orders#confirmation", as: "order_confirmation"

  # Crates --------------------------
  # resources :crates
  get "/crates", to: "crates#all", as: "all_crates"
  get "my-crates", to: "crates#my_crates", as: "my_crates"
  get "my-crates/new", to: "crates#new_my_crate", as: "new_my_crate"
  post "my-crates", to: "crates#create_my_crate", as: "create_my_crate"
  get "super-sales", to: "crates#super_sales", as: "super_sales"

   get "my-profile", to: "farmers#myprofile", as: "profile"


  # POSTS, LIKES AND COMMENTS
  get "/posts", to: "posts#all", as: "all_posts"
  get 'my-posts', to: 'posts#my_posts', as: 'my_posts'
  get 'my-posts/new', to: 'posts#new', as: 'new_post'
  post "my-posts", to: "posts#create_my_post", as: "create_my_post"



  resources :events do
    resources :event_attendances, only: [:create]
    collection do
      get "category/:category_name", to: "events#by_category", as: "by_category"
    end
  end

  resources :event_attendances, only: [:destroy] do
    collection do
      get "category/:category_name", to: "event_attendances#by_category", as: "by_category"
    end
  end
end

app/views/sections/_sidebar-1.html.erb
<nav id="sidebar" class="col-12 col-md-3 col-lg-2 bg-dark text-white p-3">
  <div class="top-section-sidebar">
        <div class="text-center mb-3">
          <%= link_to root_path do %>
            <%= image_tag "fs-icon-1.png", alt: "Logo", class: "img-fluid sidebar-logo" %>
          <% end %>
        </div>
      <hr>
      <ul class="nav flex-column">
          <li class="nav-item <%= 'active' if current_page?(root_path) %>">
              <%= link_to root_path, class: "nav-link" do %>
                <i class="fa-solid fa-house"></i> Home
              <% end %>
          </li>
          <li class="nav-item <%= 'active' if current_page?(my_crates_path) || current_page?(all_crates_path) %>">
              <%= link_to my_crates_path, class: "nav-link" do %>
                <i class="fa-solid fa-box-open"></i> Crates
              <% end %>
          </li>
          <li class="nav-item <%= 'active' if current_page?(my_events_path) || current_page?(events_path) %>">
              <%= link_to my_events_path, class: "nav-link" do %>
                <i class="fa-solid fa-earth-europe"></i> Events
              <% end %>
          </li>
         <li class="nav-item <%= 'active' if current_page?(farmers_path) %>">
              <%= link_to farmers_path, class: "nav-link" do %>
                <i class="fa-solid fa-people-roof"></i> Farmers
              <% end %>
          </li>
                 <li class="nav-item <%= 'active' if current_page?(favourites_path) %>">
              <%= link_to favourites_path, class: "nav-link" do %>
                <i class="fa-solid fa-star"></i> Favourites
              <% end %>
          </li>
          <li class="nav-item <%= 'active' if current_page?(my_posts_path) || current_page?(all_posts_path)  %>">
              <%= link_to my_posts_path, class: "nav-link" do %>
               <i class="fa-solid fa-newspaper"></i> Posts
              <% end %>
          </li>
          <li class="nav-item <%= 'active' if current_page?(profile_path) %>">
              <%= link_to profile_path, class: "nav-link" do %>
                <i class="fas fa-user me-2"></i> Profile
              <% end %>
          </li>


      </ul>
  </div>
  <div class="bottom-section-sidebar">
    <hr>
    <div class="dropdown">
      <a href="#" class="d-flex align-items-center text-decoration-none dropdown-toggle" id="dropdownUser1" data-bs-toggle="dropdown" aria-expanded="false">
        <img src="https://github.com/mdo.png" alt="" width="32" height="32" class="rounded-circle me-2">
        <strong>@<%= current_user.username %></strong>
      </a>
      <ul class="dropdown-menu dropdown-menu-dark text-small shadow" aria-labelledby="dropdownUser1">
        <li><%= link_to edit_user_registration_path, class: "dropdown-item" do %>
            <i class="fa-solid fa-gear"></i>  Settings
              <% end %>
        </li>
        <li><hr class="dropdown-divider"></li>
        <li><%= link_to "Sign out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item"  %></li>
      </ul>
    </div>
  </div>
</nav>

app/views/sections/_sidebar-2.html.erb
<nav id="sidebar" class="col-12 col-md-3 col-lg-2 bg-dark text-white p-3">
  <div class="top-section-sidebar">
        <div class="text-center mb-3">
          <%= link_to root_path do %>
            <%= image_tag "fs-icon-1.png", alt: "Logo", class: "img-fluid sidebar-logo" %>
          <% end %>
        </div>
      <hr>
      <ul class="nav flex-column">
          <li class="nav-item <%= 'active' if current_page?(root_path) %>">
              <%= link_to root_path, class: "nav-link" do %>
                <i class="fa-solid fa-house"></i> Home
              <% end %>
          </li>
          <li class="nav-item <%= 'active' if current_page?(all_crates_path) %>">
              <%= link_to all_crates_path, class: "nav-link" do %>
                <i class="fa-solid fa-box-open"></i> Crates
              <% end %>
          </li>
          <li class="nav-item <%= 'active' if current_page?(events_path) %>">
              <%= link_to events_path, class: "nav-link" do %>
                <i class="fa-solid fa-earth-europe"></i> Events
              <% end %>
          </li>
          <li class="nav-item <%= 'active' if current_page?(farmers_path) %>">
              <%= link_to farmers_path, class: "nav-link" do %>
                <i class="fa-solid fa-people-roof"></i> Farmers
              <% end %>
          </li>
                      <li class="nav-item <%= 'active' if current_page?(favourites_path) %>">
              <%= link_to favourites_path, class: "nav-link" do %>
                <i class="fa-solid fa-star"></i> Favourites
              <% end %>
          </li>
          <li class="nav-item <%= 'active' if current_page?(all_posts_path) %>">
              <%= link_to all_posts_path, class: "nav-link" do %>
               <i class="fa-solid fa-newspaper"></i> News & Updates
              <% end %>
          </li>
          <li class="nav-item <%= 'active' if current_page?(super_sales_path) %>">
              <%= link_to super_sales_path, class: "nav-link d-flex align-items-center" do %>
                <i class="fa-solid fa-percent"></i>
                <span class="ms-1">Flash Sales</span>
                <span class="badge bg-success ms-2 rounded-pill"><%= @super_sales_count %>1</span>
              <% end %>
          </li>



      </ul>
  </div>

  <div class="bottom-section-sidebar">
    <ul class="nav flex-column">
              <li class="nav-item <%= 'active' if current_page?(new_farmer_path) %>">
              <%= link_to new_farmer_path, class: "nav-link" do %>
                <i class="fa-solid fa-seedling"></i> Create A Farmer Profile
              <% end %>
          </li>
    </ul>
    <hr>
    <div class="dropdown">
      <a href="#" class="d-flex align-items-center text-decoration-none dropdown-toggle" id="dropdownUser1" data-bs-toggle="dropdown" aria-expanded="false">
        <img src="https://github.com/mdo.png" alt="" width="32" height="32" class="rounded-circle me-2">
        <strong>@<%= current_user.username %></strong>
      </a>
      <ul class="dropdown-menu dropdown-menu-dark text-small shadow" aria-labelledby="dropdownUser1">
        <li><%= link_to edit_user_registration_path, class: "dropdown-item" do %>
            <i class="fa-solid fa-gear"></i>  Settings
              <% end %>
        </li>
        <li><hr class="dropdown-divider"></li>
        <li><%= link_to "Sign out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item"  %></li>
      </ul>
    </div>
  </div>
</nav>